modLoader="javafml"
loaderVersion="[45,)"
issueTrackerURL="https://github.com/CyclopsMC/StructuredCrafting/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/structured-crafting"
license="MIT"
logoFile="logo.png"
authors="rubensworks (aka kroeser)"
[[mods]]
modId="structuredcrafting"
version="${file.jarVersion}"
displayName="StructuredCrafting"
updateJSONURL="https://raw.githubusercontent.com/CyclopsMC/Versions/master/forge_update/structured-crafting.json"
description='''
Craft stuff in your world, automatically.
'''
[[dependencies.structuredcrafting]]
    modId="cyclopscore"
    mandatory=true
    versionRange="[1.18.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.structuredcrafting]]
    modId="forge"
    mandatory=true
    versionRange="[45.0.50,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.structuredcrafting]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,]"
    ordering="NONE"
    side="BOTH"
